version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bumdesapp-be
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: bumdesapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bumdes
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
